# Generated by Django 2.2 on 2019-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190409_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertransaction',
            name='bank_name',
            field=models.CharField(default='bank_name', max_length=30),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='country',
            field=models.CharField(default='country', max_length=30),
        ),
    ]
