# Generated by Django 2.2 on 2019-04-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190411_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertransaction',
            name='to_account_name',
            field=models.CharField(default='to_account_name', max_length=30),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='to_account_number',
            field=models.CharField(default='to_account_number', max_length=30),
        ),
    ]
