# Generated by Django 2.2 on 2019-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190413_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middlename',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
