# Generated by Django 2.2 on 2019-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190427_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middlename',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
