# Generated by Django 2.2 on 2019-05-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190427_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='account_balance_on_deposit',
            field=models.IntegerField(default=0),
        ),
    ]
