# Generated by Django 2.2 on 2019-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_deposittransaction_account_balance_on_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertransaction',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='branch_code',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='reason',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='swift_code',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
